apiVersion: v1
kind: Service
metadata:
  name: travel-advisory-service
spec:
  selector:
    app: travel-advisory
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-advisory
spec:
  selector:
    matchLabels:
      app: travel-advisory
  replicas: 4
  template:
    metadata:
      labels:
        app: travel-advisory
    spec:
      containers:
      - name: travel
        image: imsuman/travel-advisory:latest
#        imagePullPolicy: Never
        ports:
        - containerPort: 5000